### ISSUE TITLE
calcHeterodimer giving different results (depending on order of the input sequences)

### ISSUE THREAD

**Issue by ffrancis** [libnano/primer3-py#16] opened 2016-02-08 23:46 UTC
calcHeterodimer(seq1, seq2) function is giving different results depending on the whether seq1 or seq2 is input first.

For example:

>>> primer3.calcHeterodimer('CTCCAGCCTCGGCAACTAAATCAG', 'CCTAGCGTTGTTAGGTGTGGCTAG')
ThermoResult(structure_found=True, tm=6.72, dg=-1866.63, dh=-86400.00, ds=-272.56)

>>> primer3.calcHeterodimer('CCTAGCGTTGTTAGGTGTGGCTAG', 'CTCCAGCCTCGGCAACTAAATCAG')
ThermoResult(structure_found=True, tm=-4.02, dg=5047.91, dh=-106700.00, ds=-360.30)

https://github.com/libnano/primer3-py/blob/master/primer3/bindings.py

**Comment by benpruitt** [comment] 2016-02-08 23:52
This issue has already been brought to the attention of the Primer3 development team and is a known bug in the thal.c code (see issue #10). I believe they are working on a fix for the next minor release of Primer3 (http://primer3.sourceforge.net/releases.php).

**Comment by benpruitt** [comment] 2016-02-08 23:53
(Closed as duplicate of #10.)

**Closed by benpruitt** 2016-02-08 23:53 UTC

**Comment by ffrancis** [comment] 2016-02-24 21:35
Hello Ben,

I contacted the primer3 development team and it seems that they have
already fixed the bug in the thal.c code ( issue #10
<https://github.com/libnano/primer3-py/issues/10>).

They have also released the next version of primer3
http://primer3.sourceforge.net/releases.php

We are using the primer3py heterodimer function in our pipeline and it
would be great if this bug gets fixed in priemr3py too, so that we can have
more reliable results.

Thank you,

Felix

On Mon, Feb 8, 2016 at 6:52 PM, Ben <notifications@github.com> wrote:

> This issue has already been brought to the attention of the Primer3
> development team and is a known bug in the thal.c code (see issue #10
> <https://github.com/libnano/primer3-py/issues/10>). I believe they are
> working on a fix for the next minor release of Primer3 (
> http://primer3.sourceforge.net/releases.php).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libnano/primer3-py/issues/16#issuecomment-181630000>.
>



-- 








*Felix FrancisBioinformatics and Systems Biology PhD candidateUniversity of
DelawarePhone : 302 887 0574 <302%20887%200574>e-mail :* ffrancis@udel.edu,
felixfrancier@gmail.com

**Comment by grinner** [comment] 2016-02-24 21:47
Thanks for drawing the new release to our attention.  The primer3 team didn't give us a heads up on the release.  We'll roll it in in short order

**Comment by ffrancis** [comment] 2016-02-24 21:51
Great! We look forward to the primer3-py update.

Thank you,

Felix

**Comment by benpruitt** [comment] 2016-02-26 19:25
Hi @ffrancis -- just wanted to let you know that we've pushed a new version of `primer3-py` that includes Primer 3 2.3.7 and corrects this calcHeterodimer issue. The new version is live [on PyPI as well](https://pypi.python.org/pypi/primer3-py), so you should be able to just run `pip install --upgrade primer3-py` to install the new version. 

Ben

**Comment by ffrancis** [comment] 2016-02-26 19:31
Great! Thank you so much for the prompt release of the updated version!

Felix
